In [59]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [3]:
OMdb = pd.read_csv('data/OMdb_mojo_clean.csv')

In [16]:
OMdb.columns

Index(['Actors', 'Awards', 'BoxOffice', 'Country', 'DVD', 'Director', 'Genre',
       'IMdb_ID', 'IMdb_score', 'Language', 'Metascore', 'Plot', 'Production',
       'RT_score', 'Rated', 'Released', 'Runtime', 'TMdb_id', 'Title', 'Type',
       'Website', 'Year', 'actor_1', 'actor_2', 'awards', 'bo_year',
       'bo_year_rank', 'director_1', 'director_2', 'domestic-gross',
       'domestic-pct', 'imdbVotes', 'itunes_id', 'logBoxOffice', 'mojo_title',
       'nominations', 'num_actor', 'num_director', 'num_genre', 'num_lang',
       'oscar_noms', 'oscar_wins', 'overseas-gross', 'overseas-pct',
       'search_strs', 'studio', 'titles', 'worldwide-gross', 'years'],
      dtype='object')

In [22]:
OMdb.dtypes

Actors              object
Awards              object
BoxOffice          float64
Country             object
DVD                 object
Director            object
Genre               object
IMdb_ID             object
IMdb_score         float64
Language            object
Metascore          float64
Plot                object
Production          object
RT_score           float64
Rated               object
Released            object
Runtime            float64
TMdb_id             object
Title               object
Type                object
Website             object
Year                 int64
actor_1             object
actor_2             object
awards             float64
bo_year            float64
bo_year_rank       float64
director_1          object
director_2          object
domestic-gross     float64
domestic-pct       float64
imdbVotes          float64
itunes_id            int64
logBoxOffice       float64
mojo_title          object
nominations        float64
num_actor            int64
num_director         int64
num_genre            int64
num_lang           float64
oscar_noms         float64
oscar_wins         float64
overseas-gross     float64
overseas-pct       float64
search_strs         object
studio              object
titles              object
worldwide-gross    float64
years                int64
dtype: object

In [50]:
OMdb.titles

0                       The Professional
1                 The Jungle Book (2016)
2               A Christmas Carol (2009)
3                                Z Storm
4                    Ghostbusters (2016)
                     ...
564                     Lords of Dogtown
565                          Bad Boys II
566               Race to Witch Mountain
567    The Hobbit: An Unexpected Journey
568           Terminator 2: Judgment Day
Name: titles, Length: 569, dtype: object

In [51]:
OMdb.Title

0                       The Professional
1                        The Jungle Book
2                      A Christmas Carol
3                                Z Storm
4                           Ghostbusters
                     ...
564                     Lords of Dogtown
565                          Bad Boys II
566               Race to Witch Mountain
567    The Hobbit: An Unexpected Journey
568           Terminator 2: Judgment Day
Name: Title, Length: 569, dtype: object

In [55]:
tmdb[tmdb.title == 'The Jungle Book (2016)']

Empty DataFrame
Columns: [budget, genres, homepage, id, keywords, original_language, original_title, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, vote_average, vote_count]
Index: []

In [4]:
tmdb = pd.read_csv('data/tmdb_5000_movies.csv')

In [11]:
tmdb.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [18]:
tmdb_new = tmdb[['title', 'budget']]

In [49]:
OMdb.merge(tmdb_new, how = 'left', left_on = 'titles', right_on = 'title')

,Actors,Awards,BoxOffice,Country,DVD,Director,Genre,IMdb_ID,IMdb_score,Language,...,oscar_wins,overseas-gross,overseas-pct,search_strs,studio,titles,worldwide-gross,years,title,budget
0,"Jean-Paul Belmondo, Jean Desailly, Cyrielle Cl...",1 win & 1 nomination.,NaN,France,30 Oct 2001,Georges Lautner,"Action, Crime, Drama, Thriller",tt0082949,76.0,French,...,0.0,36300000.0,42.5,The+Possession,LGF,The Professional,8.540000e+07,1998,NaN,NaN
1,"Neel Sethi, Bill Murray, Ben Kingsley, Idris Elba",Won 1 Oscar. Another 31 wins & 54 nominations.,363995937.0,"UK, USA",30 Aug 2016,Jon Favreau,"Adventure, Drama, Family, Fantasy",tt3040964,74.0,English,...,1.0,602500000.0,62.3,The+Jungle+Book+2016,BV,The Jungle Book (2016),9.666000e+08,2016,NaN,NaN
2,"Matt Smith, Karen Gillan, Arthur Darvill, Mich...",NaN,NaN,UK,NaN,Toby Haynes,"Adventure, Drama, Family",tt1672218,87.0,English,...,0.0,187400000.0,57.6,A+Christmas+Carol+2009,BV,A Christmas Carol (2009),3.253000e+08,2010,NaN,NaN
3,"Louis Koo, Ka Tung Lam, Dada Chan, Michael Wong",NaN,NaN,Hong Kong,NaN,David Lam,"Action, Crime",tt3469440,53.0,"Cantonese, English, Mandarin",...,0.0,2000000.0,95.4,Summer+Storm,Reg.,Z Storm,2.100000e+06,2014,Z Storm,0.0
4,"Zach Woods, Kristen Wiig, Ed Begley Jr., Charl...",5 wins & 24 nominations.,128344089.0,"USA, Australia",11 Oct 2016,Paul Feig,"Action, Comedy, Fantasy, Sci-Fi",tt1289401,53.0,English,...,0.0,100800000.0,44.0,Ghostbusters+2016,Sony,Ghostbusters (2016),2.291000e+08,2016,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,"John Robinson, Emile Hirsch, Rebecca De Mornay...",1 win & 7 nominations.,11008432.0,"USA, Germany",27 Sep 2005,Catherine Hardwicke,"Biography, Drama, Sport",tt0355702,71.0,"English, Spanish",...,0.0,2100000.0,15.9,Lords+of+Dogtown,Sony,Lords of Dogtown,1.340000e+07,2005,Lords of Dogtown,25000000.0
565,"Martin Lawrence, Will Smith, Jordi Mollà, Gabr...",5 wins & 13 nominations.,138396624.0,USA,09 Dec 2003,Michael Bay,"Action, Comedy, Crime, Drama, Thriller",tt0172156,66.0,"English, Spanish",...,0.0,134700000.0,49.3,Bad+Boys+II,Sony,Bad Boys II,2.733000e+08,2003,Bad Boys II,130000000.0
566,"Dwayne Johnson, AnnaSophia Robb, Alexander Lud...",1 nomination.,67128202.0,USA,04 Aug 2009,Andy Fickman,"Action, Adventure, Family, Fantasy, Sci-Fi, Th...",tt1075417,57.0,English,...,0.0,39200000.0,36.9,Race+to+Witch+Mountain,BV,Race to Witch Mountain,1.064000e+08,2014,Race to Witch Mountain,50000000.0
567,"Ian McKellen, Martin Freeman, Richard Armitage...",Nominated for 3 Oscars. Another 10 wins & 72 n...,303001229.0,"USA, New Zealand",19 Mar 2013,Peter Jackson,"Adventure, Family, Fantasy",tt0903624,79.0,English,...,0.0,718100000.0,70.3,The+Hobbit+An+Unexpected+Journey,WB NL,The Hobbit: An Unexpected Journey,1.021100e+09,2014,The Hobbit: An Unexpected Journey,250000000.0
568,"Arnold Schwarzenegger, Linda Hamilton, Edward ...",Won 4 Oscars. Another 27 wins & 27 nominations.,198116802.0,"USA, France",31 Mar 1998,James Cameron,"Action, Sci-Fi",tt0103064,85.0,"English, Spanish",...,4.0,315000000.0,60.6,Terminator+2+Judgment+Day,TriS,Terminator 2: Judgment Day,5.198000e+08,1997,Terminator 2: Judgment Day,100000000.0

In [27]:
all_movie = pd.read_csv('data/all_movie.csv')

In [28]:
all_movie.head()

,Cast 1,Cast 2,Cast 3,Cast 4,Cast 5,Cast 6,Description,Director 1,Director 2,Director 3,...,Rating,Release Date,Runtime,Studio,Title,Writer 1,Writer 2,Writer 3,Writer 4,Year
0,Brendan Fraser,John Hannah,Maria Bello,Michelle Yeoh,Jet Li,Russell Wong,The Fast and the Furious director Rob Cohen co...,Rob Cohen,Simon Duggan,Director Not Available,...,PG-13,7/24/2008,112 minutes,Universal Pictures,The Mummy: Tomb of the Dragon Emperor,Alfred Gough,Miles Millar,Writer Not Available,Writer Not Available,2008
1,Brett Granstaff,Diahann Carroll,Lara Jean Chorostecki,Roddy Piper,T.J. McGibbon,James Preston Rogers,The journey of a professional wrestler who bec...,Warren P. Sonoda,Director Not Available,Director Not Available,...,PG-13,1/8/2016,111 minutes,Freestyle Releasing,The Masked Saint,Scott Crowell,Brett Granstaff,Writer Not Available,Writer Not Available,2016
2,Leslie Nielsen,Nicollette Sheridan,Andy Griffith,Marcia Gay Harden,John Ales,Barry Bostwick,"Dead pan Leslie Nielsen stars as Dick Steele, ...",Rick Friedberg,Director Not Available,Director Not Available,...,PG-13,5/24/1996,80 minutes,Hollywood Pictures,Spy Hard,Rick Friedberg,Dick Chudnow,Jason Friedberg,Aaron Seltzer,1996
3,Martina Gedeck,Moritz Bleibtreu,Johanna Wokalek,Bruno Ganz,Nadja Uhl,Jan Josef Liefers,Director Uli Edel teams with screenwriter Bern...,Uli Edel,Director Not Available,Director Not Available,...,R,9/25/2008,149 minutes,Vitagraph Films,Der Baader Meinhof Komplex (The Baader Meinhof...,Uli Edel,Bernd Eichinger,Writer Not Available,Writer Not Available,2008
4,Martin Sheen,Marlon Brando,Robert Duvall,Frederic Forrest,Sam Bottoms,Laurence Fishburne,One of a cluster of late-1970s films about the...,Francis Ford Coppola,Director Not Available,Director Not Available,...,R,1/1/1979,153 minutes,United Artists,Apocalypse Now,John Milius,Francis Ford Coppola,Michael Herr,Writer Not Available,1979

In [48]:
all_movie.loc[:, (all_movie.columns.str.startswith('Write')) | (all_movie.columns == 'Title')]

,Title,Writer 1,Writer 2,Writer 3,Writer 4
0,The Mummy: Tomb of the Dragon Emperor,Alfred Gough,Miles Millar,Writer Not Available,Writer Not Available
1,The Masked Saint,Scott Crowell,Brett Granstaff,Writer Not Available,Writer Not Available
2,Spy Hard,Rick Friedberg,Dick Chudnow,Jason Friedberg,Aaron Seltzer
3,Der Baader Meinhof Komplex (The Baader Meinhof...,Uli Edel,Bernd Eichinger,Writer Not Available,Writer Not Available
4,Apocalypse Now,John Milius,Francis Ford Coppola,Michael Herr,Writer Not Available
...,...,...,...,...,...
29805,Mysterious Island,Crane Wilbur,Dan Ullman,John Prebble,Writer Not Available
29806,The Absent-Minded Professor,Bill Walsh,Writer Not Available,Writer Not Available,Writer Not Available
29807,Zardoz,John Boorman,Writer Not Available,Writer Not Available,Writer Not Available
29808,Supernova,David Campbell Wilson,David C. Wilson,Writer Not Available,Writer Not Available
29809,Battle: Los Angeles,Christopher Bertolini,Chris Bertolini,Writer Not Available,Writer Not Available

In [47]:
[all_movie.columns == 'Title']

[array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False])]

In [57]:
all_movie.columns

Index(['Cast 1', 'Cast 2', 'Cast 3', 'Cast 4', 'Cast 5', 'Cast 6',
       'Description', 'Director 1', 'Director 2', 'Director 3', 'Genre',
       'Rating', 'Release Date', 'Runtime', 'Studio', 'Title', 'Writer 1',
       'Writer 2', 'Writer 3', 'Writer 4', 'Year'],
      dtype='object')

In [ ]:
100,000,000,000